//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: tictactoe.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate V1SessionServiceClient, then call methods of this protocol to make API calls.
public protocol V1SessionServiceClientProtocol: GRPCClient {
  func join(
    _ request: JoinMessage,
    callOptions: CallOptions?
  ) -> UnaryCall<JoinMessage, JoinResponse>

  func poll(
    _ request: PollMessage,
    callOptions: CallOptions?
  ) -> UnaryCall<PollMessage, PollResponse>

}

extension V1SessionServiceClientProtocol {

  /// Unary call to join
  ///
  /// - Parameters:
  ///   - request: Request to send to join.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func join(
    _ request: JoinMessage,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<JoinMessage, JoinResponse> {
    return self.makeUnaryCall(
      path: "/V1SessionService/join",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to poll
  ///
  /// - Parameters:
  ///   - request: Request to send to poll.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func poll(
    _ request: PollMessage,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<PollMessage, PollResponse> {
    return self.makeUnaryCall(
      path: "/V1SessionService/poll",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

public final class V1SessionServiceClient: V1SessionServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the V1SessionService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// Usage: instantiate V1PlayServiceClient, then call methods of this protocol to make API calls.
public protocol V1PlayServiceClientProtocol: GRPCClient {
  func playmove(
    _ request: MoveMessage,
    callOptions: CallOptions?
  ) -> UnaryCall<MoveMessage, MoveResponse>

}

extension V1PlayServiceClientProtocol {

  /// Unary call to playmove
  ///
  /// - Parameters:
  ///   - request: Request to send to playmove.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func playmove(
    _ request: MoveMessage,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<MoveMessage, MoveResponse> {
    return self.makeUnaryCall(
      path: "/V1PlayService/playmove",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

public final class V1PlayServiceClient: V1PlayServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the V1PlayService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol V1SessionServiceProvider: CallHandlerProvider {
  func join(request: JoinMessage, context: StatusOnlyCallContext) -> EventLoopFuture<JoinResponse>
  func poll(request: PollMessage, context: StatusOnlyCallContext) -> EventLoopFuture<PollResponse>
}

extension V1SessionServiceProvider {
  public var serviceName: Substring { return "V1SessionService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "join":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.join(request: request, context: context)
        }
      }

    case "poll":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.poll(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol V1PlayServiceProvider: CallHandlerProvider {
  func playmove(request: MoveMessage, context: StatusOnlyCallContext) -> EventLoopFuture<MoveResponse>
}

extension V1PlayServiceProvider {
  public var serviceName: Substring { return "V1PlayService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "playmove":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.playmove(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

