//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: tictactoe.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate GreetServiceClient, then call methods of this protocol to make API calls.
public protocol GreetServiceClientProtocol: GRPCClient {
  func greetMe(
    _ request: GreetRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<GreetRequest, GreetResponse>

}

extension GreetServiceClientProtocol {

  /// Unary call to greetMe
  ///
  /// - Parameters:
  ///   - request: Request to send to greetMe.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func greetMe(
    _ request: GreetRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<GreetRequest, GreetResponse> {
    return self.makeUnaryCall(
      path: "/GreetService/greetMe",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

public final class GreetServiceClient: GreetServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the GreetService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol GreetServiceProvider: CallHandlerProvider {
  func greetMe(request: GreetRequest, context: StatusOnlyCallContext) -> EventLoopFuture<GreetResponse>
}

extension GreetServiceProvider {
  public var serviceName: Substring { return "GreetService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "greetMe":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.greetMe(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

