//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: webservice.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate V1UserregisterServiceClient, then call methods of this protocol to make API calls.
internal protocol V1UserregisterServiceClientProtocol: GRPCClient {
  func registeruser(
    _ request: RegisterUserMessage,
    callOptions: CallOptions?
  ) -> UnaryCall<RegisterUserMessage, UserMessage>

}

extension V1UserregisterServiceClientProtocol {

  /// Unary call to registeruser
  ///
  /// - Parameters:
  ///   - request: Request to send to registeruser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func registeruser(
    _ request: RegisterUserMessage,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<RegisterUserMessage, UserMessage> {
    return self.makeUnaryCall(
      path: "/V1UserregisterService/registeruser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class V1UserregisterServiceClient: V1UserregisterServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the V1UserregisterService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol V1UserregisterServiceProvider: CallHandlerProvider {
  func registeruser(request: RegisterUserMessage, context: StatusOnlyCallContext) -> EventLoopFuture<UserMessage>
}

extension V1UserregisterServiceProvider {
  internal var serviceName: Substring { return "V1UserregisterService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "registeruser":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.registeruser(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

